# Generated by Django 4.1.3 on 2022-11-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('cuisine', models.TextField()),
                ('description', models.TextField()),
                ('work_time', models.TextField()),
                ('menu', models.URLField()),
                ('location', models.URLField()),
            ],
        ),
    ]
