# Generated by Django 4.1.3 on 2022-11-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(default='static/images/WTE1.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
