# Generated by Django 4.1.3 on 2022-11-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wteapp', '0002_restaurant_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
