# Generated by Django 4.1.3 on 2022-11-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wteapp', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=2048)),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('cuisine', models.TextField()),
                ('description', models.TextField()),
                ('work_time', models.TextField()),
                ('menu', models.URLField()),
                ('location', models.URLField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
